apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-script-cronjob
  namespace: default  # You can change the namespace if needed
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: my-script-cronjob
        spec:
          # Specify that this job should run on Fargate
          nodeSelector:
            kubernetes.io/os: linux
          tolerations:
            - key: "eks.amazonaws.com/fargate-profile"
              operator: "Exists"
              effect: "NoSchedule"
          containers:
            - name: my-script-container
              image: <your-image-repo-url>:<your-tag>  # Replace with your Docker image URI
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "256Mi"
                  cpu: "200m"
            # Define any environment variables if needed
              env:
                - name: ENV_VAR_NAME
                  value: "value"
          restartPolicy: OnFailure
